import "dotenv/config";
import { createClient } from "@supabase/supabase-js";
import * as fs from "fs";
import * as path from "path";

const envPath = path.resolve(process.cwd(), ".env.local");
if (fs.existsSync(envPath)) {
  const lines = fs.readFileSync(envPath, "utf-8").split("\n");
  for (const line of lines) {
    const [key, ...rest] = line.split("=");
    if (key && rest.length) process.env[key.trim()] = rest.join("=").trim();
  }
}

const supabase = createClient(
  process.env.SUPABASE_URL!,
  process.env.SUPABASE_ANON_KEY!
);

async function embedText(text: string): Promise<number[]> {
  const { GoogleGenerativeAI } = await import("@google/generative-ai");
  const client = new GoogleGenerativeAI(process.env.GEMINI_API_KEY!);
  const model = client.getGenerativeModel({ model: "gemini-embedding-001" });
  const result = await model.embedContent(text);
  return result.embedding.values;
}

const recipes = [
  {
    title: "Orange Honey Yogurt Bowl",
    description: "Thick Greek yogurt layered with fresh naval orange segments, a drizzle of honey, and crunchy granola. Fast, filling, and naturally sweet.",
    ingredients: [{ name: "naval oranges", amount: "2", unit: "whole" }, { name: "Greek yogurt", amount: "1", unit: "cup" }, { name: "honey", amount: "1 tbsp", unit: "" }, { name: "granola", amount: "¼ cup", unit: "" }],
    instructions: "Peel and segment the oranges. Spoon yogurt into a bowl. Top with orange segments, drizzle honey over everything, and finish with granola.",
    fruit_tags: ["naval-oranges"],
    dietary_tags: ["vegetarian", "gluten-free", "high-protein"],
    meal_type: ["breakfast", "snack"],
    difficulty: "easy",
    prep_minutes: 5,
    servings: 1,
  },
  {
    title: "Citrus Overnight Oats",
    description: "Rolled oats soaked overnight in almond milk and brightened with fresh naval orange zest and juice. Ready when you wake up.",
    ingredients: [{ name: "rolled oats", amount: "½ cup", unit: "" }, { name: "almond milk", amount: "¾ cup", unit: "" }, { name: "naval orange", amount: "1", unit: "whole" }, { name: "chia seeds", amount: "1 tsp", unit: "" }, { name: "maple syrup", amount: "1 tsp", unit: "" }],
    instructions: "Combine oats, almond milk, chia seeds, orange zest, orange juice, and maple syrup in a jar. Stir, cover, and refrigerate overnight. Top with fresh orange segments in the morning.",
    fruit_tags: ["naval-oranges"],
    dietary_tags: ["vegan", "high-fiber", "dairy-free"],
    meal_type: ["breakfast"],
    difficulty: "easy",
    prep_minutes: 5,
    servings: 1,
  },
  {
    title: "Naval Orange Vinaigrette",
    description: "Fresh-squeezed naval orange juice emulsified with Dijon and sherry vinegar. Bright and citrusy — transforms any salad or grain bowl.",
    ingredients: [{ name: "naval oranges", amount: "2", unit: "whole" }, { name: "Dijon mustard", amount: "1 tsp", unit: "" }, { name: "sherry vinegar", amount: "1 tbsp", unit: "" }, { name: "olive oil", amount: "¼ cup", unit: "" }, { name: "salt and pepper", amount: "to taste", unit: "" }],
    instructions: "Juice the oranges. Whisk together orange juice, Dijon, and sherry vinegar. Slowly drizzle in olive oil while whisking until emulsified. Season with salt and pepper.",
    fruit_tags: ["naval-oranges"],
    dietary_tags: ["vegan", "gluten-free", "dairy-free"],
    meal_type: ["lunch", "dinner"],
    difficulty: "easy",
    prep_minutes: 5,
    servings: 4,
  },
  {
    title: "Orange Creamsicle Smoothie",
    description: "Frozen naval orange juice blended with vanilla yogurt and a splash of almond milk. Tastes exactly like the ice cream bar, but it's breakfast.",
    ingredients: [{ name: "naval oranges", amount: "3", unit: "whole" }, { name: "vanilla yogurt", amount: "½ cup", unit: "" }, { name: "almond milk", amount: "½ cup", unit: "" }, { name: "honey", amount: "1 tsp", unit: "" }, { name: "ice", amount: "1 cup", unit: "" }],
    instructions: "Juice the oranges. Add all ingredients to a blender and blend until smooth. Taste and adjust sweetness.",
    fruit_tags: ["naval-oranges"],
    dietary_tags: ["vegetarian", "gluten-free"],
    meal_type: ["breakfast", "drink", "snack"],
    difficulty: "easy",
    prep_minutes: 5,
    servings: 1,
  },
  {
    title: "Orange Glazed Roasted Carrots",
    description: "Roasted carrots finished with a sticky naval orange and honey glaze.",
    ingredients: [{ name: "carrots", amount: "1 lb", unit: "" }, { name: "naval orange", amount: "1", unit: "whole" }, { name: "honey", amount: "2 tbsp", unit: "" }, { name: "olive oil", amount: "1 tbsp", unit: "" }, { name: "salt", amount: "to taste", unit: "" }],
    instructions: "Preheat oven to 400°F. Toss carrots with olive oil and salt, roast 20 min. Whisk orange juice with honey, pour over carrots, roast another 10 min until glazed.",
    fruit_tags: ["naval-oranges"],
    dietary_tags: ["vegan", "gluten-free", "dairy-free"],
    meal_type: ["dinner", "lunch"],
    difficulty: "easy",
    prep_minutes: 10,
    servings: 4,
  },
  {
    title: "Blood Orange Arugula Salad",
    description: "Thinly sliced blood oranges fanned over peppery arugula with shaved fennel and goat cheese.",
    ingredients: [{ name: "blood oranges", amount: "3", unit: "whole" }, { name: "arugula", amount: "2 cups", unit: "" }, { name: "fennel bulb", amount: "½", unit: "" }, { name: "goat cheese", amount: "2 oz", unit: "" }, { name: "olive oil", amount: "2 tbsp", unit: "" }, { name: "flaky sea salt", amount: "to taste", unit: "" }],
    instructions: "Slice blood oranges into thin rounds. Shave fennel with a mandoline or sharp knife. Fan oranges over arugula, scatter fennel on top, crumble goat cheese, drizzle with olive oil and finish with flaky salt.",
    fruit_tags: ["blood-oranges"],
    dietary_tags: ["vegetarian", "gluten-free", "high-fiber"],
    meal_type: ["lunch", "dinner"],
    difficulty: "easy",
    prep_minutes: 10,
    servings: 2,
  },
  {
    title: "Blood Orange Agua Fresca",
    description: "Fresh blood orange juice thinned with cold water and sweetened lightly. The color is a stunning deep ruby red.",
    ingredients: [{ name: "blood oranges", amount: "6", unit: "whole" }, { name: "cold water", amount: "3 cups", unit: "" }, { name: "agave or sugar", amount: "2 tbsp", unit: "" }, { name: "ice", amount: "as needed", unit: "" }, { name: "tajín", amount: "pinch", unit: "" }],
    instructions: "Juice all blood oranges. Combine juice with water and agave, stir to dissolve. Taste and adjust sweetness. Serve over ice with a pinch of tajín on the rim.",
    fruit_tags: ["blood-oranges"],
    dietary_tags: ["vegan", "gluten-free", "dairy-free"],
    meal_type: ["drink", "snack"],
    difficulty: "easy",
    prep_minutes: 10,
    servings: 4,
  },
  {
    title: "Blood Orange Yogurt Parfait",
    description: "Layers of thick Greek yogurt, blood orange segments, and honey.",
    ingredients: [{ name: "blood oranges", amount: "2", unit: "whole" }, { name: "Greek yogurt", amount: "1 cup", unit: "" }, { name: "honey", amount: "1 tbsp", unit: "" }, { name: "pistachios", amount: "2 tbsp", unit: "chopped" }],
    instructions: "Peel and segment blood oranges. Layer yogurt, orange segments, and repeat. Drizzle honey over the top and finish with chopped pistachios.",
    fruit_tags: ["blood-oranges"],
    dietary_tags: ["vegetarian", "gluten-free", "high-protein"],
    meal_type: ["breakfast", "snack"],
    difficulty: "easy",
    prep_minutes: 5,
    servings: 1,
  },
  {
    title: "Blood Orange Pan Sauce",
    description: "A restaurant-quality pan sauce made with blood orange juice, shallots, and butter.",
    ingredients: [{ name: "blood oranges", amount: "2", unit: "whole" }, { name: "shallot", amount: "1", unit: "whole" }, { name: "butter", amount: "2 tbsp", unit: "" }, { name: "chicken or vegetable stock", amount: "¼ cup", unit: "" }, { name: "fresh thyme", amount: "2 sprigs", unit: "" }],
    instructions: "After removing protein from the pan, add minced shallot and cook 1 min. Add blood orange juice, stock, and thyme, scraping up brown bits. Simmer until reduced by half. Swirl in cold butter until glossy.",
    fruit_tags: ["blood-oranges"],
    dietary_tags: ["gluten-free"],
    meal_type: ["dinner"],
    difficulty: "intermediate",
    prep_minutes: 10,
    servings: 2,
  },
  {
    title: "Classic Lemonade",
    description: "Simple syrup, fresh lemon juice, and cold water. Made with real lemons this is so much better than anything from a bottle.",
    ingredients: [{ name: "lemons", amount: "6", unit: "whole" }, { name: "sugar", amount: "¾ cup", unit: "" }, { name: "cold water", amount: "4 cups", unit: "" }, { name: "ice", amount: "as needed", unit: "" }],
    instructions: "Make simple syrup: combine sugar with ¾ cup hot water, stir until dissolved, cool. Juice lemons. Combine syrup, lemon juice, and remaining cold water. Taste and adjust. Serve over ice.",
    fruit_tags: ["lemons"],
    dietary_tags: ["vegan", "gluten-free", "dairy-free"],
    meal_type: ["drink"],
    difficulty: "easy",
    prep_minutes: 10,
    servings: 4,
  },
  {
    title: "Lemon Pasta with Olive Oil and Parmesan",
    description: "Spaghetti tossed in lemon zest, fresh lemon juice, good olive oil, and a mountain of parmesan.",
    ingredients: [{ name: "lemons", amount: "2", unit: "whole" }, { name: "spaghetti", amount: "8 oz", unit: "" }, { name: "olive oil", amount: "¼ cup", unit: "" }, { name: "parmesan", amount: "½ cup", unit: "grated" }, { name: "garlic", amount: "2 cloves", unit: "" }, { name: "black pepper", amount: "generous", unit: "" }],
    instructions: "Cook pasta until al dente, reserve ½ cup pasta water. Sauté garlic in olive oil 1 min. Add lemon zest and juice, pasta, and pasta water. Toss vigorously until creamy. Finish with parmesan and lots of black pepper.",
    fruit_tags: ["lemons"],
    dietary_tags: ["vegetarian"],
    meal_type: ["dinner", "lunch"],
    difficulty: "easy",
    prep_minutes: 20,
    servings: 2,
  },
  {
    title: "Lemon Tahini Dressing",
    description: "Lemon juice whisked into tahini with garlic and cold water until silky. Goes on everything.",
    ingredients: [{ name: "lemons", amount: "2", unit: "whole" }, { name: "tahini", amount: "¼ cup", unit: "" }, { name: "garlic", amount: "1 clove", unit: "" }, { name: "cold water", amount: "3 tbsp", unit: "" }, { name: "salt", amount: "to taste", unit: "" }],
    instructions: "Juice lemons. Mince garlic finely. Whisk together tahini and lemon juice — it will seize up at first. Add cold water one tablespoon at a time and keep whisking until smooth and pourable. Season with salt.",
    fruit_tags: ["lemons"],
    dietary_tags: ["vegan", "gluten-free", "dairy-free"],
    meal_type: ["lunch", "dinner", "snack"],
    difficulty: "easy",
    prep_minutes: 5,
    servings: 4,
  },
  {
    title: "Preserved Lemons",
    description: "Salt-cured lemons in a jar. Takes 4 weeks to cure but then lasts months.",
    ingredients: [{ name: "lemons", amount: "8", unit: "whole" }, { name: "kosher salt", amount: "½ cup", unit: "" }, { name: "bay leaves", amount: "3", unit: "" }, { name: "black peppercorns", amount: "1 tsp", unit: "" }, { name: "extra lemon juice", amount: "to cover", unit: "" }],
    instructions: "Quarter lemons almost all the way through, keeping the base intact. Pack generously with salt inside each cut. Pack tightly into a sterilized jar with bay leaves and peppercorns. Top with extra lemon juice to cover. Seal and leave at room temperature 4 weeks, turning the jar daily.",
    fruit_tags: ["lemons"],
    dietary_tags: ["vegan", "gluten-free", "dairy-free"],
    meal_type: ["dinner"],
    difficulty: "intermediate",
    prep_minutes: 15,
    servings: 12,
  },
  {
    title: "Lemon Chia Pudding",
    description: "Chia seeds soaked in almond milk overnight with lemon zest and a little honey.",
    ingredients: [{ name: "lemons", amount: "1", unit: "whole" }, { name: "chia seeds", amount: "3 tbsp", unit: "" }, { name: "almond milk", amount: "1 cup", unit: "" }, { name: "honey", amount: "1 tbsp", unit: "" }, { name: "vanilla extract", amount: "¼ tsp", unit: "" }],
    instructions: "Whisk chia seeds, almond milk, lemon zest, lemon juice, honey, and vanilla together. Refrigerate at least 4 hours or overnight. Stir before serving.",
    fruit_tags: ["lemons"],
    dietary_tags: ["vegan", "gluten-free", "dairy-free", "high-fiber"],
    meal_type: ["breakfast", "snack"],
    difficulty: "easy",
    prep_minutes: 5,
    servings: 2,
  },
  {
    title: "Sparkling Limeade",
    description: "Fresh lime juice, a little agave, and sparkling water. Simple and refreshing.",
    ingredients: [{ name: "limes", amount: "4", unit: "whole" }, { name: "agave syrup", amount: "2 tbsp", unit: "" }, { name: "sparkling water", amount: "2 cups", unit: "" }, { name: "ice", amount: "as needed", unit: "" }, { name: "fresh mint", amount: "optional", unit: "" }],
    instructions: "Juice limes. Stir lime juice with agave until dissolved. Pour over ice, top with sparkling water, stir gently. Garnish with mint if you have it.",
    fruit_tags: ["limes"],
    dietary_tags: ["vegan", "gluten-free", "dairy-free"],
    meal_type: ["drink", "snack"],
    difficulty: "easy",
    prep_minutes: 5,
    servings: 2,
  },
  {
    title: "Lime Marinade for Chicken or Fish",
    description: "Fresh lime juice, garlic, cumin, and olive oil. Marinate for 20 minutes minimum.",
    ingredients: [{ name: "limes", amount: "3", unit: "whole" }, { name: "garlic", amount: "3 cloves", unit: "" }, { name: "cumin", amount: "1 tsp", unit: "" }, { name: "olive oil", amount: "3 tbsp", unit: "" }, { name: "salt", amount: "1 tsp", unit: "" }, { name: "black pepper", amount: "½ tsp", unit: "" }],
    instructions: "Juice limes, mince garlic. Whisk together all ingredients. Pour over protein and marinate at least 20 min in the fridge. Grill, bake, or pan-sear as usual.",
    fruit_tags: ["limes"],
    dietary_tags: ["gluten-free", "dairy-free"],
    meal_type: ["dinner", "lunch"],
    difficulty: "easy",
    prep_minutes: 5,
    servings: 2,
  },
  {
    title: "Cucumber Lime Salad",
    description: "Sliced cucumber with fresh lime juice, a little chili, and cilantro. Clean and refreshing.",
    ingredients: [{ name: "limes", amount: "2", unit: "whole" }, { name: "English cucumber", amount: "1", unit: "large" }, { name: "fresh cilantro", amount: "¼ cup", unit: "" }, { name: "red onion", amount: "¼", unit: "sliced thin" }, { name: "chili flakes", amount: "pinch", unit: "" }, { name: "salt", amount: "to taste", unit: "" }],
    instructions: "Slice cucumber thin. Toss with lime juice, cilantro, red onion, and chili flakes. Season with salt. Let sit 5 min before serving.",
    fruit_tags: ["limes"],
    dietary_tags: ["vegan", "gluten-free", "dairy-free"],
    meal_type: ["lunch", "dinner", "snack"],
    difficulty: "easy",
    prep_minutes: 10,
    servings: 2,
  },
  {
    title: "Lime Black Bean Tacos",
    description: "Canned black beans brightened with fresh lime juice, cumin, and garlic. Serve in warm corn tortillas.",
    ingredients: [{ name: "limes", amount: "2", unit: "whole" }, { name: "black beans", amount: "1 can", unit: "" }, { name: "garlic", amount: "2 cloves", unit: "" }, { name: "cumin", amount: "1 tsp", unit: "" }, { name: "corn tortillas", amount: "6", unit: "" }, { name: "salt", amount: "to taste", unit: "" }],
    instructions: "Drain and rinse beans. Cook garlic in oil 1 min, add beans and cumin, cook 3 min. Squeeze lime juice over beans, mash slightly. Warm tortillas. Serve beans in tortillas with any toppings.",
    fruit_tags: ["limes"],
    dietary_tags: ["vegan", "dairy-free", "high-fiber", "high-protein"],
    meal_type: ["lunch", "dinner"],
    difficulty: "easy",
    prep_minutes: 15,
    servings: 2,
  },
  {
    title: "Pomegranate Walnut Salad",
    description: "Mixed greens with pomegranate arils, toasted walnuts, and crumbled feta, dressed with a honey-balsamic vinaigrette.",
    ingredients: [{ name: "pomegranates", amount: "1", unit: "whole" }, { name: "mixed greens", amount: "4 cups", unit: "" }, { name: "walnuts", amount: "¼ cup", unit: "toasted" }, { name: "feta cheese", amount: "2 oz", unit: "" }, { name: "balsamic vinegar", amount: "1 tbsp", unit: "" }, { name: "honey", amount: "1 tsp", unit: "" }, { name: "olive oil", amount: "2 tbsp", unit: "" }],
    instructions: "Seed the pomegranate (do it in a bowl of water to avoid mess). Whisk balsamic, honey, and olive oil for dressing. Toss greens with dressing. Top with pomegranate arils, walnuts, and crumbled feta.",
    fruit_tags: ["pomegranates"],
    dietary_tags: ["vegetarian", "gluten-free", "high-fiber"],
    meal_type: ["lunch", "dinner"],
    difficulty: "easy",
    prep_minutes: 15,
    servings: 2,
  },
  {
    title: "Pomegranate Molasses",
    description: "Pomegranate juice reduced with sugar and lemon until thick and syrupy. Use on roasted meats, drizzled on yogurt, or stirred into cocktails.",
    ingredients: [{ name: "pomegranates", amount: "3", unit: "whole" }, { name: "sugar", amount: "¼ cup", unit: "" }, { name: "lemon", amount: "1", unit: "whole" }],
    instructions: "Juice pomegranates — you need about 2 cups juice. Combine juice, sugar, and lemon juice in a small saucepan. Simmer over medium-low heat 45-60 min until reduced to about ½ cup and thick enough to coat a spoon. Cool — it thickens more as it cools.",
    fruit_tags: ["pomegranates"],
    dietary_tags: ["vegan", "gluten-free", "dairy-free"],
    meal_type: ["dinner", "snack"],
    difficulty: "intermediate",
    prep_minutes: 60,
    servings: 8,
  },
  {
    title: "Pomegranate Overnight Oats",
    description: "Oats soaked overnight with pomegranate juice and topped with fresh arils in the morning.",
    ingredients: [{ name: "pomegranates", amount: "1", unit: "whole" }, { name: "rolled oats", amount: "½ cup", unit: "" }, { name: "almond milk", amount: "½ cup", unit: "" }, { name: "pomegranate juice", amount: "¼ cup", unit: "" }, { name: "honey", amount: "1 tbsp", unit: "" }, { name: "chia seeds", amount: "1 tsp", unit: "" }],
    instructions: "Seed the pomegranate and set aside arils. Mix oats, almond milk, pomegranate juice, honey, and chia seeds in a jar. Refrigerate overnight. Top with fresh arils before serving.",
    fruit_tags: ["pomegranates"],
    dietary_tags: ["vegan", "dairy-free", "high-fiber"],
    meal_type: ["breakfast"],
    difficulty: "easy",
    prep_minutes: 5,
    servings: 1,
  },
  {
    title: "Pomegranate Quinoa Bowl",
    description: "Cooked quinoa topped with pomegranate arils, cucumber, fresh mint, and a lemon-olive oil dressing.",
    ingredients: [{ name: "pomegranates", amount: "1", unit: "whole" }, { name: "quinoa", amount: "1 cup", unit: "cooked" }, { name: "cucumber", amount: "½", unit: "diced" }, { name: "fresh mint", amount: "¼ cup", unit: "" }, { name: "olive oil", amount: "2 tbsp", unit: "" }, { name: "lemon", amount: "1", unit: "juiced" }, { name: "salt", amount: "to taste", unit: "" }],
    instructions: "Cook quinoa per package instructions and cool to room temp. Seed pomegranate. Combine quinoa, pomegranate arils, cucumber, and mint. Dress with olive oil and lemon juice, season with salt.",
    fruit_tags: ["pomegranates"],
    dietary_tags: ["vegan", "gluten-free", "dairy-free", "high-protein", "high-fiber"],
    meal_type: ["lunch", "dinner"],
    difficulty: "easy",
    prep_minutes: 20,
    servings: 2,
  },
  {
    title: "Avocado Toast with Lemon and Flaky Salt",
    description: "Ripe Hass avocado smashed on thick sourdough toast, finished with fresh lemon juice and flaky salt.",
    ingredients: [{ name: "avocados", amount: "1", unit: "ripe" }, { name: "sourdough bread", amount: "2 slices", unit: "" }, { name: "lemons", amount: "½", unit: "" }, { name: "flaky sea salt", amount: "pinch", unit: "" }, { name: "red pepper flakes", amount: "optional", unit: "" }],
    instructions: "Toast bread until golden and crisp. Halve and pit the avocado, scoop flesh into a bowl, and smash with a fork — leave it chunky. Spread on toast, squeeze lemon over the top, finish with flaky salt and pepper flakes.",
    fruit_tags: ["avocados", "lemons"],
    dietary_tags: ["vegan", "dairy-free", "high-fiber"],
    meal_type: ["breakfast", "lunch", "snack"],
    difficulty: "easy",
    prep_minutes: 5,
    servings: 1,
  },
  {
    title: "Classic Guacamole",
    description: "Perfectly ripe Hass avocados mashed with lime juice, cilantro, red onion, and jalapeño.",
    ingredients: [{ name: "avocados", amount: "3", unit: "ripe" }, { name: "limes", amount: "2", unit: "whole" }, { name: "red onion", amount: "¼", unit: "finely diced" }, { name: "jalapeño", amount: "1", unit: "seeded and minced" }, { name: "fresh cilantro", amount: "¼ cup", unit: "chopped" }, { name: "kosher salt", amount: "½ tsp", unit: "" }],
    instructions: "Halve and pit avocados. Scoop flesh into a bowl. Squeeze in lime juice, add salt, and mash to your desired texture. Fold in red onion, jalapeño, and cilantro. Taste and adjust lime and salt.",
    fruit_tags: ["avocados", "limes"],
    dietary_tags: ["vegan", "gluten-free", "dairy-free"],
    meal_type: ["snack", "lunch", "dinner"],
    difficulty: "easy",
    prep_minutes: 10,
    servings: 4,
  },
  {
    title: "Avocado Citrus Salad",
    description: "Sliced avocado and blood orange over arugula with a citrus vinaigrette.",
    ingredients: [{ name: "avocados", amount: "2", unit: "ripe" }, { name: "blood-oranges", amount: "2", unit: "whole" }, { name: "arugula", amount: "2 cups", unit: "" }, { name: "olive oil", amount: "2 tbsp", unit: "" }, { name: "lemon", amount: "½", unit: "" }, { name: "flaky salt", amount: "to taste", unit: "" }],
    instructions: "Slice avocados and orange into rounds. Fan over arugula. Drizzle with olive oil, squeeze lemon, and finish with flaky salt.",
    fruit_tags: ["avocados", "blood-oranges"],
    dietary_tags: ["vegan", "gluten-free", "dairy-free", "high-fiber"],
    meal_type: ["lunch", "dinner"],
    difficulty: "easy",
    prep_minutes: 10,
    servings: 2,
  },
  {
    title: "Avocado Green Smoothie",
    description: "Half an avocado blended with almond milk, spinach, lime juice, and honey. A genuinely filling breakfast.",
    ingredients: [{ name: "avocados", amount: "½", unit: "ripe" }, { name: "limes", amount: "1", unit: "whole" }, { name: "baby spinach", amount: "1 cup", unit: "" }, { name: "almond milk", amount: "1 cup", unit: "" }, { name: "honey", amount: "1 tbsp", unit: "" }, { name: "ice", amount: "½ cup", unit: "" }],
    instructions: "Juice the lime. Add all ingredients to a blender and blend until completely smooth.",
    fruit_tags: ["avocados", "limes"],
    dietary_tags: ["vegan", "gluten-free", "dairy-free"],
    meal_type: ["breakfast", "drink", "snack"],
    difficulty: "easy",
    prep_minutes: 5,
    servings: 1,
  },
  {
    title: "Avocado Egg Scramble",
    description: "Soft scrambled eggs topped with sliced avocado, a squeeze of lime, and everything bagel seasoning.",
    ingredients: [{ name: "avocados", amount: "1", unit: "ripe" }, { name: "limes", amount: "½", unit: "" }, { name: "eggs", amount: "3", unit: "" }, { name: "butter", amount: "1 tsp", unit: "" }, { name: "everything bagel seasoning", amount: "1 tsp", unit: "" }, { name: "salt", amount: "to taste", unit: "" }],
    instructions: "Whisk eggs with a pinch of salt. Melt butter over low heat, add eggs, and stir constantly until just barely set. Plate, top with sliced avocado, squeeze lime juice, and sprinkle everything bagel seasoning.",
    fruit_tags: ["avocados", "limes"],
    dietary_tags: ["vegetarian", "gluten-free", "high-protein"],
    meal_type: ["breakfast"],
    difficulty: "easy",
    prep_minutes: 10,
    servings: 1,
  },
  {
    title: "Citrus Fruit Salad",
    description: "Naval oranges, blood oranges, and pomegranate arils tossed with a little honey and fresh mint.",
    ingredients: [{ name: "naval-oranges", amount: "2", unit: "whole" }, { name: "blood-oranges", amount: "2", unit: "whole" }, { name: "pomegranates", amount: "½", unit: "whole" }, { name: "honey", amount: "1 tbsp", unit: "" }, { name: "fresh mint", amount: "¼ cup", unit: "" }],
    instructions: "Peel and segment all citrus, removing as much pith as possible. Seed the pomegranate half. Combine fruit in a bowl, drizzle honey, tear mint leaves over the top. Toss gently.",
    fruit_tags: ["naval-oranges", "blood-oranges", "pomegranates"],
    dietary_tags: ["vegan", "gluten-free", "dairy-free", "high-fiber"],
    meal_type: ["breakfast", "snack"],
    difficulty: "easy",
    prep_minutes: 10,
    servings: 3,
  },
  {
    title: "Orange Ricotta Pancakes",
    description: "Fluffy ricotta pancakes with fresh naval orange zest and juice folded into the batter. Serve with a drizzle of honey.",
    ingredients: [{ name: "naval oranges", amount: "2", unit: "whole" }, { name: "ricotta", amount: "¾ cup", unit: "" }, { name: "eggs", amount: "2", unit: "" }, { name: "flour", amount: "½ cup", unit: "" }, { name: "honey", amount: "2 tbsp", unit: "" }, { name: "baking powder", amount: "1 tsp", unit: "" }],
    instructions: "Zest and juice one orange. Whisk ricotta, eggs, orange zest, orange juice, and honey. Fold in flour and baking powder. Cook on buttered skillet over medium heat until bubbles form, flip once. Serve with sliced orange segments.",
    fruit_tags: ["naval-oranges"],
    dietary_tags: ["vegetarian", "high-protein"],
    meal_type: ["breakfast"],
    difficulty: "easy",
    prep_minutes: 20,
    servings: 2,
  },
  {
    title: "Orange Glazed Salmon",
    description: "Pan-seared salmon glazed with a sticky reduction of naval orange juice, soy sauce, and ginger.",
    ingredients: [{ name: "naval oranges", amount: "3", unit: "whole" }, { name: "salmon fillets", amount: "2", unit: "" }, { name: "soy sauce", amount: "2 tbsp", unit: "" }, { name: "fresh ginger", amount: "1 tsp", unit: "grated" }, { name: "garlic", amount: "1 clove", unit: "" }, { name: "olive oil", amount: "1 tbsp", unit: "" }],
    instructions: "Juice oranges. Combine juice, soy sauce, ginger, and garlic in a small pan and reduce until syrupy, about 5 minutes. Sear salmon in oil over high heat 3 min per side. Brush glaze over salmon in the last minute of cooking.",
    fruit_tags: ["naval-oranges"],
    dietary_tags: ["gluten-free", "dairy-free", "high-protein"],
    meal_type: ["dinner"],
    difficulty: "intermediate",
    prep_minutes: 20,
    servings: 2,
  },
  {
    title: "Orange Lentil Soup",
    description: "Red lentil soup brightened at the end with a big squeeze of naval orange juice. Warming, filling, and naturally vegan.",
    ingredients: [{ name: "naval oranges", amount: "2", unit: "whole" }, { name: "red lentils", amount: "1 cup", unit: "" }, { name: "vegetable broth", amount: "4 cups", unit: "" }, { name: "cumin", amount: "2 tsp", unit: "" }, { name: "turmeric", amount: "½ tsp", unit: "" }, { name: "garlic", amount: "3 cloves", unit: "" }, { name: "olive oil", amount: "2 tbsp", unit: "" }],
    instructions: "Sauté garlic in olive oil 1 min. Add lentils, cumin, turmeric, and broth. Simmer 20 min until lentils are very soft. Squeeze in orange juice and adjust seasoning. Blend partially if you prefer a thicker texture.",
    fruit_tags: ["naval-oranges"],
    dietary_tags: ["vegan", "gluten-free", "dairy-free", "high-fiber", "high-protein"],
    meal_type: ["lunch", "dinner"],
    difficulty: "easy",
    prep_minutes: 30,
    servings: 3,
  },
  {
    title: "Warm Spiced Orange Drink",
    description: "Fresh naval orange juice heated with cinnamon, cloves, and honey. A soothing non-alcoholic warm drink.",
    ingredients: [{ name: "naval oranges", amount: "4", unit: "whole" }, { name: "honey", amount: "2 tbsp", unit: "" }, { name: "cinnamon stick", amount: "1", unit: "" }, { name: "cloves", amount: "3", unit: "whole" }, { name: "water", amount: "1 cup", unit: "" }],
    instructions: "Juice oranges. Combine juice, water, cinnamon, and cloves in a small saucepan. Heat over low until steaming, about 5 minutes. Do not boil. Remove spices, stir in honey, and serve in mugs.",
    fruit_tags: ["naval-oranges"],
    dietary_tags: ["vegan", "gluten-free", "dairy-free"],
    meal_type: ["drink"],
    difficulty: "easy",
    prep_minutes: 10,
    servings: 2,
  },
  {
    title: "Orange Poppy Seed Dressing",
    description: "A bright, creamy dressing made with fresh naval orange juice, Dijon, and poppy seeds. Perfect on spinach or grain salads.",
    ingredients: [{ name: "naval oranges", amount: "2", unit: "whole" }, { name: "Dijon mustard", amount: "1 tsp", unit: "" }, { name: "honey", amount: "1 tbsp", unit: "" }, { name: "apple cider vinegar", amount: "1 tbsp", unit: "" }, { name: "olive oil", amount: "3 tbsp", unit: "" }, { name: "poppy seeds", amount: "1 tsp", unit: "" }],
    instructions: "Juice oranges. Whisk together orange juice, Dijon, honey, and vinegar. Stream in olive oil while whisking until emulsified. Stir in poppy seeds. Keeps in the fridge for a week.",
    fruit_tags: ["naval-oranges"],
    dietary_tags: ["vegetarian", "gluten-free", "dairy-free"],
    meal_type: ["lunch", "snack"],
    difficulty: "easy",
    prep_minutes: 5,
    servings: 4,
  },
  {
    title: "Segmented Orange Salad with Fennel",
    description: "Naval orange segments fanned over shaved fennel with olive oil and flaky salt. Clean, simple, beautiful.",
    ingredients: [{ name: "naval oranges", amount: "3", unit: "whole" }, { name: "fennel bulb", amount: "1", unit: "small, shaved thin" }, { name: "olive oil", amount: "2 tbsp", unit: "" }, { name: "flaky sea salt", amount: "pinch", unit: "" }, { name: "black pepper", amount: "to taste", unit: "" }],
    instructions: "Supreme the oranges: slice off ends, cut away peel and pith, then cut between membranes to release segments. Shave fennel thin on a mandoline or with a sharp knife. Arrange fennel on a plate, top with orange segments, drizzle olive oil, and season with flaky salt.",
    fruit_tags: ["naval-oranges"],
    dietary_tags: ["vegan", "gluten-free", "dairy-free"],
    meal_type: ["lunch", "dinner", "snack"],
    difficulty: "easy",
    prep_minutes: 10,
    servings: 2,
  },
  {
    title: "Orange Polenta Porridge",
    description: "Creamy stovetop polenta sweetened with naval orange juice and zest, topped with a drizzle of honey.",
    ingredients: [{ name: "naval oranges", amount: "2", unit: "whole" }, { name: "polenta", amount: "½ cup", unit: "" }, { name: "whole milk", amount: "2 cups", unit: "" }, { name: "honey", amount: "2 tbsp", unit: "" }, { name: "butter", amount: "1 tbsp", unit: "" }, { name: "salt", amount: "pinch", unit: "" }],
    instructions: "Zest and juice one orange. Bring milk to a gentle simmer in a saucepan. Whisk in polenta slowly. Cook 10 min stirring often until thick and creamy. Stir in butter, orange zest, half the juice, and honey. Serve topped with fresh orange segments.",
    fruit_tags: ["naval-oranges"],
    dietary_tags: ["vegetarian", "gluten-free"],
    meal_type: ["breakfast"],
    difficulty: "easy",
    prep_minutes: 15,
    servings: 2,
  },
  {
    title: "Blood Orange Chia Pudding",
    description: "Chia seeds soaked overnight in coconut milk with blood orange juice stirred through, creating a stunning pink-crimson pudding.",
    ingredients: [{ name: "blood oranges", amount: "3", unit: "whole" }, { name: "chia seeds", amount: "3 tbsp", unit: "" }, { name: "coconut milk", amount: "1 cup", unit: "" }, { name: "honey", amount: "1 tbsp", unit: "" }],
    instructions: "Juice blood oranges. Whisk together coconut milk, blood orange juice, and honey. Stir in chia seeds and whisk again after 5 minutes to break up clumps. Refrigerate overnight. Top with fresh blood orange segments before serving.",
    fruit_tags: ["blood-oranges"],
    dietary_tags: ["vegan", "gluten-free", "dairy-free", "high-fiber"],
    meal_type: ["breakfast", "snack"],
    difficulty: "easy",
    prep_minutes: 5,
    servings: 2,
  },
  {
    title: "Blood Orange Ricotta Toast",
    description: "Thick toast spread with creamy ricotta and topped with thin blood orange slices, honey, and fresh thyme.",
    ingredients: [{ name: "blood oranges", amount: "2", unit: "whole" }, { name: "thick bread", amount: "2 slices", unit: "" }, { name: "ricotta", amount: "¼ cup", unit: "" }, { name: "honey", amount: "1 tbsp", unit: "" }, { name: "fresh thyme", amount: "few sprigs", unit: "" }],
    instructions: "Toast bread. Spread ricotta generously. Slice blood oranges thin and arrange over ricotta. Drizzle honey, scatter fresh thyme leaves.",
    fruit_tags: ["blood-oranges"],
    dietary_tags: ["vegetarian"],
    meal_type: ["breakfast", "snack"],
    difficulty: "easy",
    prep_minutes: 5,
    servings: 1,
  },
  {
    title: "Roasted Carrots with Blood Orange Glaze",
    description: "Whole roasted carrots glazed with blood orange juice, olive oil, and honey. A stunning side dish.",
    ingredients: [{ name: "blood oranges", amount: "2", unit: "whole" }, { name: "carrots", amount: "1 lb", unit: "whole" }, { name: "olive oil", amount: "2 tbsp", unit: "" }, { name: "honey", amount: "1 tbsp", unit: "" }, { name: "salt", amount: "½ tsp", unit: "" }, { name: "fresh thyme", amount: "optional", unit: "" }],
    instructions: "Preheat oven to 425°F. Juice oranges. Toss carrots with olive oil, salt, and half the juice. Roast 25-30 min until tender and caramelizing. In the last 5 min, drizzle remaining juice and honey over carrots and return to oven.",
    fruit_tags: ["blood-oranges"],
    dietary_tags: ["vegan", "gluten-free", "dairy-free"],
    meal_type: ["dinner", "lunch"],
    difficulty: "easy",
    prep_minutes: 35,
    servings: 3,
  },
  {
    title: "Blood Orange Granita",
    description: "A simple Sicilian-style frozen dessert made with blood orange juice and sugar. Scrape into icy flakes and serve in chilled glasses.",
    ingredients: [{ name: "blood oranges", amount: "6", unit: "whole" }, { name: "sugar", amount: "¼ cup", unit: "" }, { name: "water", amount: "¼ cup", unit: "" }],
    instructions: "Juice blood oranges. Make a simple syrup by heating sugar and water until dissolved. Combine juice and cooled syrup. Pour into a shallow dish and freeze. Every 30 min for 3 hours, scrape with a fork to create icy flakes. Serve in chilled glasses.",
    fruit_tags: ["blood-oranges"],
    dietary_tags: ["vegan", "gluten-free", "dairy-free"],
    meal_type: ["snack"],
    difficulty: "easy",
    prep_minutes: 15,
    servings: 4,
  },
  {
    title: "Blood Orange Sparkling Mocktail",
    description: "Blood orange juice over ice with sparkling water and a splash of bitters. Looks like a cocktail, tastes even better.",
    ingredients: [{ name: "blood oranges", amount: "4", unit: "whole" }, { name: "sparkling water", amount: "1 cup", unit: "" }, { name: "honey", amount: "1 tbsp", unit: "" }, { name: "ice", amount: "as needed", unit: "" }, { name: "rosemary sprig", amount: "optional", unit: "" }],
    instructions: "Juice blood oranges. Stir juice with honey until dissolved. Fill a glass with ice, pour juice mixture halfway, top with sparkling water. Garnish with a rosemary sprig if you have it.",
    fruit_tags: ["blood-oranges"],
    dietary_tags: ["vegan", "gluten-free", "dairy-free"],
    meal_type: ["drink"],
    difficulty: "easy",
    prep_minutes: 5,
    servings: 2,
  },
  {
    title: "Blood Orange Vinaigrette",
    description: "A crimson vinaigrette made with fresh blood orange juice, sherry vinegar, and Dijon. Transforms any salad.",
    ingredients: [{ name: "blood oranges", amount: "2", unit: "whole" }, { name: "sherry vinegar", amount: "1 tbsp", unit: "" }, { name: "Dijon mustard", amount: "1 tsp", unit: "" }, { name: "olive oil", amount: "¼ cup", unit: "" }, { name: "honey", amount: "1 tsp", unit: "" }, { name: "salt", amount: "to taste", unit: "" }],
    instructions: "Juice blood oranges. Whisk together juice, vinegar, Dijon, and honey. Slowly drizzle in olive oil while whisking to emulsify. Season with salt. Use immediately or store in the fridge up to one week.",
    fruit_tags: ["blood-oranges"],
    dietary_tags: ["vegan", "gluten-free", "dairy-free"],
    meal_type: ["lunch", "dinner"],
    difficulty: "easy",
    prep_minutes: 5,
    servings: 4,
  },
  {
    title: "Blood Orange Smoothie",
    description: "Blood orange juice blended with frozen banana and Greek yogurt. Deep crimson color and a creamy, tart flavor.",
    ingredients: [{ name: "blood oranges", amount: "3", unit: "whole" }, { name: "frozen banana", amount: "1", unit: "" }, { name: "Greek yogurt", amount: "½ cup", unit: "" }, { name: "honey", amount: "1 tsp", unit: "" }, { name: "ice", amount: "½ cup", unit: "" }],
    instructions: "Juice blood oranges. Blend all ingredients until completely smooth. Add more juice or ice to adjust consistency.",
    fruit_tags: ["blood-oranges"],
    dietary_tags: ["vegetarian", "gluten-free", "high-protein"],
    meal_type: ["breakfast", "drink", "snack"],
    difficulty: "easy",
    prep_minutes: 5,
    servings: 1,
  },
  {
    title: "Lemon Ricotta Toast",
    description: "Whipped ricotta on toasted bread with lemon zest and a drizzle of honey. Creamy, bright, and done in 5 minutes.",
    ingredients: [{ name: "lemons", amount: "1", unit: "whole" }, { name: "sourdough bread", amount: "2 slices", unit: "" }, { name: "ricotta", amount: "¼ cup", unit: "" }, { name: "honey", amount: "1 tbsp", unit: "" }, { name: "flaky sea salt", amount: "pinch", unit: "" }],
    instructions: "Toast bread. Whip ricotta with a fork until light. Spread on toast, zest lemon generously over the top, drizzle honey, and finish with flaky salt.",
    fruit_tags: ["lemons"],
    dietary_tags: ["vegetarian"],
    meal_type: ["breakfast", "snack"],
    difficulty: "easy",
    prep_minutes: 5,
    servings: 1,
  },
  {
    title: "Lemon Herb Roasted Chicken Thighs",
    description: "Bone-in chicken thighs marinated in lemon juice, garlic, oregano, and olive oil, then roasted until crispy-skinned.",
    ingredients: [{ name: "lemons", amount: "2", unit: "whole" }, { name: "chicken thighs", amount: "4", unit: "bone-in" }, { name: "garlic", amount: "4 cloves", unit: "" }, { name: "dried oregano", amount: "1 tbsp", unit: "" }, { name: "olive oil", amount: "3 tbsp", unit: "" }, { name: "salt and pepper", amount: "to taste", unit: "" }],
    instructions: "Marinate chicken in lemon juice, garlic, oregano, olive oil, salt and pepper for at least 30 min. Preheat oven to 425°F. Roast chicken skin-side up for 35-40 min until skin is deeply golden and internal temp reaches 165°F.",
    fruit_tags: ["lemons"],
    dietary_tags: ["gluten-free", "dairy-free", "high-protein"],
    meal_type: ["dinner"],
    difficulty: "easy",
    prep_minutes: 45,
    servings: 4,
  },
  {
    title: "Lemon Orzo Soup",
    description: "A simple, soothing soup with orzo pasta, spinach, and a generous squeeze of lemon at the end. Greek-inspired.",
    ingredients: [{ name: "lemons", amount: "2", unit: "whole" }, { name: "orzo", amount: "½ cup", unit: "" }, { name: "vegetable broth", amount: "4 cups", unit: "" }, { name: "baby spinach", amount: "2 cups", unit: "" }, { name: "garlic", amount: "2 cloves", unit: "" }, { name: "olive oil", amount: "2 tbsp", unit: "" }],
    instructions: "Sauté garlic in olive oil. Add broth and bring to a boil. Add orzo and cook 8 min. Add spinach and cook 1 more min until wilted. Remove from heat and squeeze in lemon juice generously. Season and serve.",
    fruit_tags: ["lemons"],
    dietary_tags: ["vegan", "dairy-free", "high-fiber"],
    meal_type: ["lunch", "dinner"],
    difficulty: "easy",
    prep_minutes: 20,
    servings: 3,
  },
  {
    title: "Lemon Honey Ginger Tea",
    description: "Hot water with fresh lemon juice, raw honey, and grated ginger. Simple and genuinely good.",
    ingredients: [{ name: "lemons", amount: "1", unit: "whole" }, { name: "fresh ginger", amount: "1 inch", unit: "piece" }, { name: "raw honey", amount: "2 tbsp", unit: "" }, { name: "hot water", amount: "2 cups", unit: "" }],
    instructions: "Juice lemon. Grate ginger. Combine lemon juice, ginger, and honey in a mug. Pour hot water over and stir until honey dissolves. Let sit 1 minute before drinking.",
    fruit_tags: ["lemons"],
    dietary_tags: ["vegan", "gluten-free", "dairy-free"],
    meal_type: ["drink"],
    difficulty: "easy",
    prep_minutes: 5,
    servings: 2,
  },
  {
    title: "Lemon Roasted Asparagus",
    description: "Asparagus roasted at high heat and finished with fresh lemon juice and zest. A ten-minute side dish.",
    ingredients: [{ name: "lemons", amount: "1", unit: "whole" }, { name: "asparagus", amount: "1 bunch", unit: "" }, { name: "olive oil", amount: "2 tbsp", unit: "" }, { name: "garlic", amount: "2 cloves", unit: "minced" }, { name: "salt and pepper", amount: "to taste", unit: "" }],
    instructions: "Preheat oven to 425°F. Toss asparagus with olive oil, garlic, salt, and pepper. Roast 10-12 min until tender and slightly charred. Remove from oven, squeeze lemon over the top and zest generously.",
    fruit_tags: ["lemons"],
    dietary_tags: ["vegan", "gluten-free", "dairy-free"],
    meal_type: ["dinner", "lunch"],
    difficulty: "easy",
    prep_minutes: 15,
    servings: 2,
  },
  {
    title: "Lemon Bars",
    description: "A buttery shortbread base with a tangy, set lemon curd on top. Dusted with powdered sugar.",
    ingredients: [{ name: "lemons", amount: "3", unit: "whole" }, { name: "flour", amount: "1 cup", unit: "" }, { name: "butter", amount: "½ cup", unit: "" }, { name: "powdered sugar", amount: "¼ cup", unit: "" }, { name: "eggs", amount: "3", unit: "" }, { name: "sugar", amount: "1 cup", unit: "" }],
    instructions: "Make crust: mix flour, butter, and powdered sugar. Press into a greased 8x8 pan and bake at 350°F for 15 min. Make filling: whisk eggs, sugar, lemon juice, and zest. Pour over crust. Bake 20 more min until set. Cool completely, dust with powdered sugar, cut into bars.",
    fruit_tags: ["lemons"],
    dietary_tags: ["vegetarian"],
    meal_type: ["snack"],
    difficulty: "intermediate",
    prep_minutes: 50,
    servings: 9,
  },
  {
    title: "Lemon Garlic Pasta",
    description: "Simple pasta tossed with lemon zest, lemon juice, garlic, olive oil, and Parmesan. Ready in 15 minutes.",
    ingredients: [{ name: "lemons", amount: "2", unit: "whole" }, { name: "pasta", amount: "8 oz", unit: "" }, { name: "garlic", amount: "4 cloves", unit: "" }, { name: "olive oil", amount: "¼ cup", unit: "" }, { name: "Parmesan", amount: "½ cup", unit: "grated" }, { name: "salt and pepper", amount: "to taste", unit: "" }],
    instructions: "Cook pasta al dente, reserve 1 cup pasta water. Sauté garlic in olive oil until golden. Add lemon zest and juice, pasta, and splash of pasta water. Toss until saucy, adding more water as needed. Plate and top with Parmesan.",
    fruit_tags: ["lemons"],
    dietary_tags: ["vegetarian"],
    meal_type: ["dinner", "lunch"],
    difficulty: "easy",
    prep_minutes: 20,
    servings: 3,
  },
  {
    title: "Lime Coconut Chia Pudding",
    description: "Coconut milk chia pudding brightened with fresh lime juice and zest. Tropical and refreshing.",
    ingredients: [{ name: "limes", amount: "2", unit: "whole" }, { name: "chia seeds", amount: "3 tbsp", unit: "" }, { name: "coconut milk", amount: "1 cup", unit: "" }, { name: "maple syrup", amount: "1 tbsp", unit: "" }, { name: "coconut flakes", amount: "2 tbsp", unit: "toasted" }],
    instructions: "Zest and juice limes. Whisk coconut milk, lime juice, zest, and maple syrup. Stir in chia seeds. Refrigerate overnight or at least 4 hours. Top with toasted coconut flakes before serving.",
    fruit_tags: ["limes"],
    dietary_tags: ["vegan", "gluten-free", "dairy-free", "high-fiber"],
    meal_type: ["breakfast", "snack"],
    difficulty: "easy",
    prep_minutes: 5,
    servings: 2,
  },
  {
    title: "Agua de Lima",
    description: "Mexican lime water — fresh lime juice, water, sugar, and a pinch of salt. Clean, simple, perfect.",
    ingredients: [{ name: "limes", amount: "6", unit: "whole" }, { name: "water", amount: "4 cups", unit: "" }, { name: "sugar", amount: "3 tbsp", unit: "" }, { name: "salt", amount: "pinch", unit: "" }, { name: "ice", amount: "as needed", unit: "" }],
    instructions: "Juice limes. Combine lime juice, water, sugar, and salt. Stir until sugar dissolves. Serve over ice. Add more lime or sugar to taste.",
    fruit_tags: ["limes"],
    dietary_tags: ["vegan", "gluten-free", "dairy-free"],
    meal_type: ["drink"],
    difficulty: "easy",
    prep_minutes: 5,
    servings: 4,
  },
  {
    title: "Thai Lime Noodles",
    description: "Rice noodles dressed in a punchy lime, fish sauce, and sesame sauce with fresh herbs and crushed peanuts.",
    ingredients: [{ name: "limes", amount: "3", unit: "whole" }, { name: "rice noodles", amount: "6 oz", unit: "" }, { name: "fish sauce", amount: "2 tbsp", unit: "" }, { name: "sesame oil", amount: "1 tbsp", unit: "" }, { name: "peanuts", amount: "¼ cup", unit: "crushed" }, { name: "fresh cilantro", amount: "¼ cup", unit: "" }, { name: "scallions", amount: "3", unit: "" }],
    instructions: "Cook rice noodles per package and rinse cold. Whisk lime juice, fish sauce, and sesame oil. Toss noodles in dressing. Top with peanuts, cilantro, and sliced scallions. Serve at room temp.",
    fruit_tags: ["limes"],
    dietary_tags: ["dairy-free", "gluten-free"],
    meal_type: ["lunch", "dinner"],
    difficulty: "easy",
    prep_minutes: 20,
    servings: 2,
  },
  {
    title: "Chili Lime Roasted Chickpeas",
    description: "Crispy roasted chickpeas tossed with fresh lime juice, chili powder, and salt. A crunchy snack.",
    ingredients: [{ name: "limes", amount: "2", unit: "whole" }, { name: "chickpeas", amount: "1 can", unit: "drained and dried" }, { name: "olive oil", amount: "2 tbsp", unit: "" }, { name: "chili powder", amount: "1 tsp", unit: "" }, { name: "cumin", amount: "½ tsp", unit: "" }, { name: "salt", amount: "½ tsp", unit: "" }],
    instructions: "Preheat oven to 400°F. Pat chickpeas completely dry. Toss with olive oil, chili, cumin, and salt. Spread on a baking sheet and roast 30-35 min until crispy, shaking pan halfway. Remove from oven and immediately squeeze lime juice over, toss, and sprinkle with more salt.",
    fruit_tags: ["limes"],
    dietary_tags: ["vegan", "gluten-free", "dairy-free", "high-protein", "high-fiber"],
    meal_type: ["snack"],
    difficulty: "easy",
    prep_minutes: 40,
    servings: 3,
  },
  {
    title: "Lime Slaw",
    description: "Shredded cabbage tossed with a bright lime, olive oil, and honey dressing. The perfect crunchy side.",
    ingredients: [{ name: "limes", amount: "2", unit: "whole" }, { name: "green cabbage", amount: "½ head", unit: "shredded" }, { name: "carrot", amount: "1", unit: "shredded" }, { name: "olive oil", amount: "2 tbsp", unit: "" }, { name: "honey", amount: "1 tsp", unit: "" }, { name: "salt", amount: "to taste", unit: "" }],
    instructions: "Shred cabbage and carrot. Juice limes. Whisk lime juice, olive oil, honey, and salt to make dressing. Toss vegetables in dressing. Let sit 10 min before serving so cabbage softens slightly.",
    fruit_tags: ["limes"],
    dietary_tags: ["vegan", "gluten-free", "dairy-free", "high-fiber"],
    meal_type: ["lunch", "dinner", "snack"],
    difficulty: "easy",
    prep_minutes: 15,
    servings: 4,
  },
  {
    title: "Lime Butter",
    description: "Softened butter whipped with lime zest and a pinch of salt. Spread on corn, fish, or vegetables.",
    ingredients: [{ name: "limes", amount: "2", unit: "whole" }, { name: "butter", amount: "½ cup", unit: "softened" }, { name: "flaky salt", amount: "pinch", unit: "" }],
    instructions: "Zest limes and squeeze a little juice. Beat butter until fluffy. Fold in lime zest, a squeeze of juice, and flaky salt. Roll in plastic wrap and refrigerate until firm. Slice into rounds.",
    fruit_tags: ["limes"],
    dietary_tags: ["vegetarian", "gluten-free"],
    meal_type: ["snack", "dinner"],
    difficulty: "easy",
    prep_minutes: 10,
    servings: 8,
  },
  {
    title: "Pomegranate Smoothie Bowl",
    description: "A thick blended smoothie bowl made with pomegranate juice, frozen banana, and topped with fresh arils.",
    ingredients: [{ name: "pomegranates", amount: "2", unit: "whole" }, { name: "frozen banana", amount: "1", unit: "" }, { name: "Greek yogurt", amount: "¼ cup", unit: "" }, { name: "granola", amount: "¼ cup", unit: "" }, { name: "honey", amount: "1 tsp", unit: "" }],
    instructions: "Seed pomegranates, reserve arils. Juice half the pomegranate. Blend juice, frozen banana, and yogurt until thick and smooth. Pour into a bowl. Top with remaining arils, granola, and a drizzle of honey.",
    fruit_tags: ["pomegranates"],
    dietary_tags: ["vegetarian", "gluten-free", "high-protein"],
    meal_type: ["breakfast"],
    difficulty: "easy",
    prep_minutes: 10,
    servings: 1,
  },
  {
    title: "Pomegranate Lentil Salad",
    description: "French green lentils with pomegranate arils, fresh herbs, and a tangy vinaigrette. Hearty and full of texture.",
    ingredients: [{ name: "pomegranates", amount: "1", unit: "whole" }, { name: "French green lentils", amount: "1 cup", unit: "" }, { name: "vegetable broth", amount: "2 cups", unit: "" }, { name: "fresh parsley", amount: "½ cup", unit: "" }, { name: "red onion", amount: "¼", unit: "finely diced" }, { name: "olive oil", amount: "3 tbsp", unit: "" }, { name: "red wine vinegar", amount: "2 tbsp", unit: "" }],
    instructions: "Cook lentils in broth until tender, about 20 min. Drain and cool. Seed pomegranate. Toss lentils with pomegranate arils, parsley, red onion, olive oil, and red wine vinegar. Season and serve at room temp.",
    fruit_tags: ["pomegranates"],
    dietary_tags: ["vegan", "gluten-free", "dairy-free", "high-fiber", "high-protein"],
    meal_type: ["lunch", "dinner"],
    difficulty: "easy",
    prep_minutes: 30,
    servings: 3,
  },
  {
    title: "Pomegranate Glazed Carrots",
    description: "Roasted carrots finished with a pomegranate molasses glaze. Sweet, earthy, and deeply flavored.",
    ingredients: [{ name: "pomegranates", amount: "2", unit: "whole" }, { name: "carrots", amount: "1 lb", unit: "" }, { name: "olive oil", amount: "2 tbsp", unit: "" }, { name: "honey", amount: "2 tbsp", unit: "" }, { name: "salt", amount: "½ tsp", unit: "" }],
    instructions: "Juice pomegranates and simmer juice with honey until reduced to a glaze, about 10 min. Roast carrots at 425°F with olive oil and salt for 25 min. Brush with glaze and roast 5 more minutes. Top with pomegranate arils if available.",
    fruit_tags: ["pomegranates"],
    dietary_tags: ["vegan", "gluten-free", "dairy-free"],
    meal_type: ["dinner", "lunch"],
    difficulty: "easy",
    prep_minutes: 40,
    servings: 3,
  },
  {
    title: "Sparkling Pomegranate Mocktail",
    description: "Fresh pomegranate juice over ice with sparkling water, a squeeze of lime, and a sugared rim.",
    ingredients: [{ name: "pomegranates", amount: "2", unit: "whole" }, { name: "sparkling water", amount: "1 cup", unit: "" }, { name: "honey", amount: "1 tbsp", unit: "" }, { name: "ice", amount: "as needed", unit: "" }, { name: "fresh mint", amount: "optional", unit: "" }],
    instructions: "Seed and juice pomegranates. Stir juice with honey. Fill a glass with ice, add juice halfway, top with sparkling water. Garnish with mint.",
    fruit_tags: ["pomegranates"],
    dietary_tags: ["vegan", "gluten-free", "dairy-free"],
    meal_type: ["drink"],
    difficulty: "easy",
    prep_minutes: 10,
    servings: 2,
  },
  {
    title: "Persian-Style Pomegranate Chicken",
    description: "Chicken simmered in a pomegranate and walnut sauce — a simplified version of the classic Persian fesenjan.",
    ingredients: [{ name: "pomegranates", amount: "2", unit: "whole" }, { name: "chicken thighs", amount: "4", unit: "boneless" }, { name: "walnuts", amount: "1 cup", unit: "finely ground" }, { name: "onion", amount: "1", unit: "diced" }, { name: "olive oil", amount: "2 tbsp", unit: "" }, { name: "turmeric", amount: "½ tsp", unit: "" }, { name: "salt", amount: "to taste", unit: "" }],
    instructions: "Juice pomegranates. Brown chicken in oil, remove. Sauté onion until soft. Add ground walnuts, pomegranate juice, turmeric, and 1 cup water. Simmer 15 min. Return chicken, cover and simmer 20 more min until sauce is thick. Serve over rice.",
    fruit_tags: ["pomegranates"],
    dietary_tags: ["gluten-free", "dairy-free", "high-protein"],
    meal_type: ["dinner"],
    difficulty: "intermediate",
    prep_minutes: 50,
    servings: 4,
  },
  {
    title: "Pomegranate Dark Chocolate Bark",
    description: "Melted dark chocolate spread thin and topped with pomegranate arils and flaky salt. Freezes in 20 minutes.",
    ingredients: [{ name: "pomegranates", amount: "1", unit: "whole" }, { name: "dark chocolate", amount: "6 oz", unit: "70%+" }, { name: "flaky sea salt", amount: "pinch", unit: "" }],
    instructions: "Seed pomegranate. Melt chocolate carefully over a double boiler or in microwave in 30-second bursts. Spread thin on parchment paper. Scatter pomegranate arils over the top and press gently. Sprinkle flaky salt. Freeze 20 min until set. Break into pieces.",
    fruit_tags: ["pomegranates"],
    dietary_tags: ["vegan", "gluten-free", "dairy-free"],
    meal_type: ["snack"],
    difficulty: "easy",
    prep_minutes: 30,
    servings: 6,
  },
  {
    title: "Smashed Avocado Breakfast Bowl",
    description: "Smashed avocado over warm brown rice with a soft-boiled egg and everything bagel seasoning.",
    ingredients: [{ name: "avocados", amount: "1", unit: "ripe" }, { name: "brown rice", amount: "1 cup", unit: "cooked" }, { name: "eggs", amount: "2", unit: "" }, { name: "everything bagel seasoning", amount: "1 tsp", unit: "" }, { name: "red pepper flakes", amount: "pinch", unit: "" }, { name: "salt", amount: "to taste", unit: "" }],
    instructions: "Soft-boil eggs 7 min, peel and halve. Warm rice. Smash avocado with salt. Spoon rice into bowl, top with smashed avocado, halved eggs, everything bagel seasoning, and pepper flakes.",
    fruit_tags: ["avocados"],
    dietary_tags: ["vegetarian", "gluten-free", "dairy-free", "high-protein"],
    meal_type: ["breakfast", "lunch"],
    difficulty: "easy",
    prep_minutes: 15,
    servings: 1,
  },
  {
    title: "Avocado Smoothie",
    description: "Creamy avocado blended with banana, almond milk, and honey. Rich and filling breakfast drink.",
    ingredients: [{ name: "avocados", amount: "½", unit: "ripe" }, { name: "frozen banana", amount: "1", unit: "" }, { name: "almond milk", amount: "1 cup", unit: "" }, { name: "honey", amount: "1 tbsp", unit: "" }, { name: "vanilla extract", amount: "½ tsp", unit: "" }, { name: "ice", amount: "½ cup", unit: "" }],
    instructions: "Add all ingredients to a blender and blend until completely smooth and creamy. Taste and add more honey if needed.",
    fruit_tags: ["avocados"],
    dietary_tags: ["vegan", "gluten-free", "dairy-free"],
    meal_type: ["breakfast", "drink", "snack"],
    difficulty: "easy",
    prep_minutes: 5,
    servings: 1,
  },
  {
    title: "Baked Egg in Avocado",
    description: "An avocado half with the pit removed, an egg cracked directly inside, and baked until the white is just set.",
    ingredients: [{ name: "avocados", amount: "2", unit: "ripe" }, { name: "eggs", amount: "4", unit: "" }, { name: "salt and pepper", amount: "to taste", unit: "" }, { name: "paprika", amount: "pinch", unit: "" }, { name: "fresh chives", amount: "optional", unit: "" }],
    instructions: "Preheat oven to 425°F. Halve avocados and remove pits. Scoop out a little extra flesh to make room for the egg. Place in a baking dish and crack an egg into each half. Season with salt, pepper, and paprika. Bake 12-15 min until whites are set but yolk is still runny.",
    fruit_tags: ["avocados"],
    dietary_tags: ["vegetarian", "gluten-free", "dairy-free", "high-protein"],
    meal_type: ["breakfast"],
    difficulty: "easy",
    prep_minutes: 20,
    servings: 2,
  },
  {
    title: "Stuffed Avocado with Quinoa",
    description: "Avocado halves stuffed with herbed quinoa, cucumber, and sun-dried tomatoes. A complete no-cook lunch.",
    ingredients: [{ name: "avocados", amount: "2", unit: "ripe" }, { name: "quinoa", amount: "1 cup", unit: "cooked" }, { name: "cucumber", amount: "½", unit: "diced" }, { name: "sun-dried tomatoes", amount: "3 tbsp", unit: "" }, { name: "fresh parsley", amount: "¼ cup", unit: "" }, { name: "olive oil", amount: "2 tbsp", unit: "" }, { name: "salt", amount: "to taste", unit: "" }],
    instructions: "Cook and cool quinoa. Mix with cucumber, sun-dried tomatoes, parsley, olive oil, and salt. Halve avocados and remove pit. Pile quinoa filling into each avocado half and serve.",
    fruit_tags: ["avocados"],
    dietary_tags: ["vegan", "gluten-free", "dairy-free", "high-protein", "high-fiber"],
    meal_type: ["lunch"],
    difficulty: "easy",
    prep_minutes: 15,
    servings: 2,
  },
  {
    title: "Avocado Pasta",
    description: "Ripe avocado blended into a creamy, dairy-free pasta sauce with garlic and basil.",
    ingredients: [{ name: "avocados", amount: "2", unit: "ripe" }, { name: "pasta", amount: "8 oz", unit: "" }, { name: "garlic", amount: "2 cloves", unit: "" }, { name: "fresh basil", amount: "½ cup", unit: "" }, { name: "olive oil", amount: "2 tbsp", unit: "" }, { name: "salt and pepper", amount: "to taste", unit: "" }],
    instructions: "Cook pasta al dente, reserve ½ cup pasta water. Blend avocado flesh, garlic, basil, olive oil, and pasta water until smooth and creamy. Toss warm pasta with avocado sauce. Add more pasta water if needed. Serve immediately.",
    fruit_tags: ["avocados"],
    dietary_tags: ["vegan", "dairy-free"],
    meal_type: ["dinner", "lunch"],
    difficulty: "easy",
    prep_minutes: 20,
    servings: 3,
  },
  {
    title: "Avocado Hummus",
    description: "Classic hummus blended with ripe avocado for an extra creamy, richer version. Serve with pita or vegetables.",
    ingredients: [{ name: "avocados", amount: "1", unit: "ripe" }, { name: "chickpeas", amount: "1 can", unit: "drained" }, { name: "tahini", amount: "3 tbsp", unit: "" }, { name: "garlic", amount: "1 clove", unit: "" }, { name: "olive oil", amount: "2 tbsp", unit: "" }, { name: "cumin", amount: "½ tsp", unit: "" }, { name: "salt", amount: "to taste", unit: "" }],
    instructions: "Blend all ingredients in a food processor until very smooth, about 3 minutes. Stream in a little cold water to achieve desired consistency. Season with salt. Drizzle olive oil to serve.",
    fruit_tags: ["avocados"],
    dietary_tags: ["vegan", "gluten-free", "dairy-free", "high-fiber", "high-protein"],
    meal_type: ["snack", "lunch"],
    difficulty: "easy",
    prep_minutes: 10,
    servings: 4,
  },
  {
    title: "Avocado Chocolate Mousse",
    description: "Silky chocolate mousse made with ripe avocado instead of cream. Tastes like dessert, eats like a health food.",
    ingredients: [{ name: "avocados", amount: "2", unit: "ripe" }, { name: "cocoa powder", amount: "¼ cup", unit: "" }, { name: "honey", amount: "3 tbsp", unit: "" }, { name: "vanilla extract", amount: "1 tsp", unit: "" }, { name: "almond milk", amount: "2 tbsp", unit: "" }, { name: "flaky salt", amount: "pinch", unit: "" }],
    instructions: "Blend all ingredients until completely smooth and fluffy. Taste and adjust sweetness. Refrigerate at least 30 min before serving. Top with flaky salt.",
    fruit_tags: ["avocados"],
    dietary_tags: ["vegan", "gluten-free", "dairy-free"],
    meal_type: ["snack"],
    difficulty: "easy",
    prep_minutes: 10,
    servings: 3,
  },
  {
    title: "Avocado Gazpacho",
    description: "A creamy green cold soup made with avocado, cucumber, and herbs. No cooking required.",
    ingredients: [{ name: "avocados", amount: "2", unit: "ripe" }, { name: "cucumber", amount: "1", unit: "peeled" }, { name: "vegetable broth", amount: "1 cup", unit: "cold" }, { name: "garlic", amount: "1 clove", unit: "" }, { name: "olive oil", amount: "2 tbsp", unit: "" }, { name: "fresh dill", amount: "¼ cup", unit: "" }, { name: "salt", amount: "to taste", unit: "" }],
    instructions: "Blend all ingredients until completely smooth. Season with salt. Refrigerate at least 1 hour until very cold. Serve in chilled bowls drizzled with olive oil.",
    fruit_tags: ["avocados"],
    dietary_tags: ["vegan", "gluten-free", "dairy-free"],
    meal_type: ["lunch", "dinner"],
    difficulty: "easy",
    prep_minutes: 10,
    servings: 3,
  },
  {
    title: "Avocado Rice Bowl",
    description: "Warm jasmine rice topped with sliced avocado, sesame seeds, scallions, and a drizzle of soy sauce.",
    ingredients: [{ name: "avocados", amount: "1", unit: "ripe" }, { name: "jasmine rice", amount: "1 cup", unit: "cooked" }, { name: "soy sauce", amount: "1 tbsp", unit: "" }, { name: "sesame oil", amount: "1 tsp", unit: "" }, { name: "sesame seeds", amount: "1 tsp", unit: "" }, { name: "scallions", amount: "2", unit: "sliced" }],
    instructions: "Cook rice. Slice avocado. Drizzle rice with soy sauce and sesame oil. Top with avocado slices, sesame seeds, and scallions. Serve warm.",
    fruit_tags: ["avocados"],
    dietary_tags: ["vegan", "dairy-free"],
    meal_type: ["lunch", "dinner"],
    difficulty: "easy",
    prep_minutes: 15,
    servings: 1,
  },
  {
    title: "Avocado Herb Dip",
    description: "Blended avocado with fresh herbs, garlic, and olive oil. Thinner than guacamole, better for dipping or drizzling.",
    ingredients: [{ name: "avocados", amount: "2", unit: "ripe" }, { name: "fresh basil", amount: "¼ cup", unit: "" }, { name: "fresh chives", amount: "2 tbsp", unit: "" }, { name: "garlic", amount: "1 clove", unit: "" }, { name: "olive oil", amount: "3 tbsp", unit: "" }, { name: "salt", amount: "to taste", unit: "" }, { name: "water", amount: "2 tbsp", unit: "" }],
    instructions: "Blend all ingredients until very smooth. Adjust water for a thinner consistency. Season generously with salt. Serve with crudités or chips.",
    fruit_tags: ["avocados"],
    dietary_tags: ["vegan", "gluten-free", "dairy-free"],
    meal_type: ["snack", "lunch"],
    difficulty: "easy",
    prep_minutes: 5,
    servings: 4,
  },
  {
    title: "Avocado Orange Salsa",
    description: "Diced avocado and naval orange with red onion, cilantro, and lime. Goes on grilled fish or chicken, or eaten straight with tortilla chips.",
    ingredients: [{ name: "avocados", amount: "1", unit: "ripe" }, { name: "naval-oranges", amount: "1", unit: "whole" }, { name: "limes", amount: "1", unit: "whole" }, { name: "red onion", amount: "¼", unit: "finely diced" }, { name: "fresh cilantro", amount: "3 tbsp", unit: "" }, { name: "jalapeño", amount: "½", unit: "optional" }, { name: "salt", amount: "to taste", unit: "" }],
    instructions: "Dice avocado and orange into similar-sized pieces. Combine with red onion, cilantro, and jalapeño if using. Squeeze lime juice over the top, season with salt. Serve immediately.",
    fruit_tags: ["avocados", "naval-oranges", "limes"],
    dietary_tags: ["vegan", "gluten-free", "dairy-free"],
    meal_type: ["snack", "lunch", "dinner"],
    difficulty: "easy",
    prep_minutes: 10,
    servings: 2,
  },
];

function buildEmbedText(recipe: typeof recipes[0]): string {
  return [
    recipe.title,
    recipe.description,
    `Uses: ${recipe.fruit_tags.join(", ")}.`,
    `Tags: ${recipe.dietary_tags.join(", ")}.`,
    `Meal type: ${recipe.meal_type.join(", ")}.`,
    `Difficulty: ${recipe.difficulty}.`,
    recipe.prep_minutes ? `${recipe.prep_minutes} minutes.` : "",
  ]
    .filter(Boolean)
    .join(" ");
}

async function main() {
  console.log(`\nSeeding ${recipes.length} recipes into Supabase...\n`);

  if (!process.env.SUPABASE_URL || !process.env.SUPABASE_ANON_KEY) {
    console.error("Missing required env vars. Make sure .env.local has SUPABASE_URL and SUPABASE_ANON_KEY.");
    process.exit(1);
  }

  console.log("Clearing existing recipes...");
  await supabase.from("recipes").delete().neq("id", "00000000-0000-0000-0000-000000000000");
  console.log("Cleared.\n");

  let successCount = 0;
  let errorCount = 0;

  for (const recipe of recipes) {
    process.stdout.write(`  ${recipe.title}... `);

    try {
      const { data, error: insertError } = await supabase
        .from("recipes")
        .insert({
          title: recipe.title,
          description: recipe.description,
          ingredients: recipe.ingredients,
          instructions: recipe.instructions,
          fruit_tags: recipe.fruit_tags,
          dietary_tags: recipe.dietary_tags,
          meal_type: recipe.meal_type,
          difficulty: recipe.difficulty,
          prep_minutes: recipe.prep_minutes,
          servings: recipe.servings,
        })
        .select("id")
        .single();

      if (insertError) throw insertError;

      const text = buildEmbedText(recipe);
      const embedding = await embedText(text);

      const { error: updateError } = await supabase
        .from("recipes")
        .update({ embedding })
        .eq("id", data.id);

      if (updateError) throw updateError;

      console.log("done");
      successCount++;

      await new Promise((r) => setTimeout(r, 500));
    } catch (err) {
      console.log("FAILED");
      console.error(`    Error: ${err instanceof Error ? err.message : err}`);
      errorCount++;
    }
  }

  console.log(`\nDone. ${successCount} succeeded, ${errorCount} failed.\n`);
}

main();
